services:
  - type: web
    name: my-laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    branch: main
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: "My Laravel App"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: my-laravel-app
          property: host
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_STDERR_FORMATTER
        value: Monolog\Formatter\JsonFormatter
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: my-laravel-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: my-laravel-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: my-laravel-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: my-laravel-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: my-laravel-db
          property: password
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: VITE_APP_NAME
        value: "My Laravel App"

databases:
  - name: my-laravel-db
    databaseName: laravel_app
    user: laravel_user
    plan: starter