services:
  - type: web
    name: my-laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    branch: main
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: "My Laravel App"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: my-laravel-app
          property: host
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_STDERR_FORMATTER
        value: Monolog\Formatter\JsonFormatter
      - key: DB_CONNECTION
        value: sqlite
      - key: CACHE_STORE
        value: database
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: VITE_APP_NAME
        value: "My Laravel App"

